jobs:
  - job: test
    pool: Default
    container: debian:stretch
    steps:
      - bash: |
          apt-get install software-properties-common
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
          apt-add-repository "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main"
          apt-get update
          apt-get install libllvm-7-ocaml-dev libllvm7 llvm-7 llvm-7-dev llvm-7-doc llvm-7-examples llvm-7-runtime
        displayName: 'Install LLVM'
      - bash: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          export PATH=$PATH:$HOME/.cargo/bin
        displayName: 'Install rust'
      - bash: cargo build --all --verbose
        displayName: 'Build (debug)'
      - bash: cargo test --all --verbose
        displayName: 'Test'
      - bash: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings
        displayName: 'Clippy'
