jobs:
  - job: test
    pool: Default
    container: rust:latest
    steps:
      - script: |
          deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main
          deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main
        displayName: 'Install LLVM'
      - script: cargo build --all --verbose
        displayName: 'Build (debug)'
      - script: cargo test --all --verbose
        displayName: 'Test'
      - script: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings
        displayName: 'Clippy'
