jobs:
  - job: test
    container: debian-stretch:latest
    steps:
      - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
        displayName: 'Install rust'
      - script: cargo build --all --verbose
        displayName: 'Build (debug)'
      - script: cargo test --all --verbose
        displayName: 'Test'
      - script: |
          rustup component add clippy
          cargo clippy --all-targets --all-features -- -D warnings
        displayName: 'Clippy'
