jobs:
  - job: test
    pool: Default
    container: kittylang/archlinux-llvm7-rust:latest
    - bash: cargo build --all --verbose
      displayName: 'Build (debug)'
    - bash: cargo test --all --verbose
      displayName: 'Test'
    - bash: |
        rustup component add clippy
        cargo clippy --all-targets --all-features -- -D warnings
      displayName: 'Clippy'
